<?php
$data = array (
  0 => 
  array (
    'cat_id' => '90',
    'cat_name' => '测试数据3',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '6',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'type_img' => '',
    'goods_num' => '2',
  ),
  2 => 
  array (
    'cat_id' => '81',
    'cat_name' => '测试',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '21',
    'cat_name' => '客餐厅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'type_img' => '',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '1',
    'cat_name' => '卧房',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '5',
    'type_img' => '',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '22',
    'cat_name' => '厨房',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'type_img' => '',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '12',
    'cat_name' => '充值卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '62',
    'cat_name' => '建材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '23',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '20',
    'cat_name' => '青少年房',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'type_img' => '',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '3',
    'cat_name' => '整体衣柜',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '4',
    'type_img' => '',
    'goods_num' => '10',
  ),
  11 => 
  array (
    'cat_id' => '4',
    'cat_name' => '衣帽间',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => '2',
  ),
  12 => 
  array (
    'cat_id' => '69',
    'cat_name' => '飘窗利用',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '5',
    'cat_name' => '定制床',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 2,
  ),
  14 => 
  array (
    'cat_id' => '2',
    'cat_name' => '米兰范儿卧房',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'type_img' => '',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '87',
    'cat_name' => '测试数据8',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '60',
    'cat_name' => '测试数据3',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '84',
    'cat_name' => '测试数据6',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '82',
    'cat_name' => '测试数据4',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '58',
    'cat_name' => '测试数据1',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '95',
    'cat_name' => '测试数据9',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '85',
    'cat_name' => '测试数据7',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '83',
    'cat_name' => '测试数据5',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '59',
    'cat_name' => '测试数据2',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '52',
    'cat_name' => '测试数据4',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '49',
    'cat_name' => '测试数据1',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '50',
    'cat_name' => '测试数据2',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '51',
    'cat_name' => '测试数据3',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '55',
    'cat_name' => '测试数据3',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '53',
    'cat_name' => '测试数据1',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '54',
    'cat_name' => '测试数据2',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '94',
    'cat_name' => '测试数据3',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '88',
    'cat_name' => '测试数据1',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '89',
    'cat_name' => '测试数据2',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '70',
    'cat_name' => '绕线器',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '9',
    'cat_name' => '韩式田园书房',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '71',
    'cat_name' => '多功能床',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '11',
    'cat_name' => '榻榻米',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '2',
  ),
  38 => 
  array (
    'cat_id' => '7',
    'cat_name' => '直角书桌组合',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '72',
    'cat_name' => '转角书桌组合',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '8',
    'cat_name' => '书柜组合',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => '3',
  ),
  41 => 
  array (
    'cat_id' => '46',
    'cat_name' => '测试数据5',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '45',
    'cat_name' => '测试数据4',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '47',
    'cat_name' => '测试数据6',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '48',
    'cat_name' => '测试数据7',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '41',
    'cat_name' => '测试数据',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '39',
    'cat_name' => '原装电池',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '40',
    'cat_name' => '电池测试2',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '13',
    'cat_name' => '小灵通/固话充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '14',
    'cat_name' => '移动手机充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '15',
    'cat_name' => '联通手机充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '32',
    'cat_name' => '储物间',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '67',
    'cat_name' => '榻榻米',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '65',
    'cat_name' => '衣柜组合',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '68',
    'cat_name' => '上下床组合',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '30',
    'cat_name' => '床组合',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '31',
    'cat_name' => '飘窗学习区',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '66',
    'cat_name' => '风衣',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '73',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '77',
    'cat_name' => '沙发茶几组合',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '74',
    'cat_name' => '餐桌组合',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '33',
    'cat_name' => '餐柜组合',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '78',
    'cat_name' => '吧台组合',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '75',
    'cat_name' => '隔断柜组合',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '34',
    'cat_name' => '羽绒服',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '76',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '29',
    'cat_name' => '一字型',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'L型',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '27',
    'cat_name' => 'U型',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '79',
    'cat_name' => '英伦晴风',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '28',
    'cat_name' => '新实用厨房',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '37',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '38',
    'cat_name' => '运动包',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '63',
    'cat_name' => '卫浴用品',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '64',
    'cat_name' => '灯饰照明',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '93',
    'cat_name' => '测试数据3',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '91',
    'cat_name' => '测试数据1',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '92',
    'cat_name' => '测试数据2',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
);
?>